#cloud-config
users:
  - name: ubuntu
    groups: [users, admin]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcAlV9W9OGR7DrLRhf9lAy2eLvlKP5YJIvt+4lCfLyHkwwwEtWMZi9qM30zmym917xv87VxUKasKeRF+YUNnjB+LjLjQKnY4P++jaJ1WiQi/ghDKvxxzsdg24Y1WOGeuOYZjb+reNrpLaIEWr6DJfNGUh72A/JRBkjpzyLvlXuOCxDQGGigfXCH0q9tA95g5Uw43hFecxZmqgTaJFwJSbd3OlvSBLy1GBQ+CVNrHZcWzikTZOTcLexrXPuvi17VctpHRrXq7GfNQJ/lCe171qXfEZcj9yada3J7y1QUS6gps+hQqmLVuTcBTIQUW/4WCjkIFPer2zneCyHeNZ5E5ER aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
package_update: true
packages:
  - apache2
  - php
  - libapache2-mod-php
  - php-mysql
  - adminer

write_files:
  - path: /var/www/html/index.html
    content: |
      <h1>testtest</h1>
  - path: /var/www/html/info.php
    content: |
      <?php phpinfo(); ?>
  - path: /var/www/html/db.php
    content: |
      <?php
      $h="172.31.22.122"; $u="webuser"; $p="webpass"; $d="webdb";
      mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
      try { $c = new mysqli($h,$u,$p,$d); echo "Connected successfully to the database!"; }
      catch (Exception $e) { echo "DB ERROR: ".$e->getMessage(); }
      ?>

runcmd:
  - a2enconf adminer
  - systemctl enable --now apache2
  - systemctl restart apache2
